# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04b_classification.modelling.meta_arch.ipynb (unless otherwise specified).

__all__ = ['GeneralizedImageClassifier']

# Cell
from typing import *

import numpy as np
import torch
from fastcore.all import Transform, delegates, typedispatch, use_kwargs_dict
from PIL import Image
from torch.nn import Module

from .backbones import ImageClassificationBackbone
from .heads import ImageClassificationHead
from ...core.classes import GaleModule
from ...core.logging import setup_logger

# Cell
class GeneralizedImageClassifier(GaleModule):
