# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.logging.ipynb (unless otherwise specified).

__all__ = ['setup_logger']

# Cell
import logging
import sys

import loguru
from fastcore.all import delegates

# Cell
@delegates(loguru.logger.add)
def setup_logger(
    sink=sys.stdout,
    level=logging.INFO,
    format="<green>[{time:MM/DD HH:mm:ss} {name}]</green> <lvl>{level}</lvl>: {message}",
    colorize=True,
    **kwargs
):
    "Default logger for the Gale Library"
    logger = loguru.logger
    logger.remove()
    logger.add(sink, level=level, format=format, colorize=colorize, **kwargs)
    return logger